# use Ganache's forked mainnet mode as the default network
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.0.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"
networks:
  default: mainnet-fork
  mainnet-fork:
    aave_lending_pool_v2: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  kovan:
    aave_lending_pool_v2: "0x88757f2f99175387ab4c6a4b3067c77a695b0349"
    weth: "0xff795577d9ac8bd7d90ee22b6c1703490b6512fd"
    # DAI
    # weth: "0xd0a1e359811322d97991e03f863a0c30c2cf029c"
  mainnet:
    aave_lending_pool_v2: "0xB53C1a33016B2DC2fF3653530bfF1848a515c8c5"
    weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  ropsten:
    aave_lending_pool_v2: "0x1c8756FD2B28e9426CDBDcC7E3c4d64fa9A54728"
    weth: "0xad6d458402f60fd3bd25163575031acdce07538d"
wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
